name: infrastructure_firebase
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: any
  cloud_functions: any
  collection: any
  fcm_config: ^3.6.5
  firebase_analytics: any
  firebase_app_check: any
  firebase_auth: any
  firebase_core: any
  firebase_crashlytics: any
  firebase_remote_config: any
  firebase_storage: any
  flutter:
    sdk: flutter
  flutter_image_compress: any
  flutter_localizations:
    sdk: flutter
  freezed_annotation: any
  google_sign_in: any
  intl: any
  json_serializable: any
  logger: any
  nested: any
  packages_core:
    path: ../../core
  packages_domain:
    path: ../../domain
  riverpod: any
  riverpod_annotation: any
  uuid: any
  version: any

dev_dependencies:
  alchemist: ^0.12.1
  build_runner: any
  custom_lint: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
  freezed: null
  nilts: ^0.23.1
  pedantic_mono: any
  riverpod_generator: any
  riverpod_lint: any

resolution: workspace
