name: infrastructure_firebase
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.1

dependencies:
  cloud_firestore: ^6.1.0
  cloud_functions: ^6.0.4
  cross_file: ^0.3.5+1
  envied: ^1.3.1
  fcm_config: ^3.6.5
  firebase_analytics: ^12.0.4
  firebase_app_check: ^0.4.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  firebase_remote_config: ^6.1.2
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  nested: ^1.0.0
  packages_core:
    path: ../../core
  packages_domain:
    path: ../../domain
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  envied_generator: ^1.3.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  nilts: ^0.25.1
  pedantic_mono: ^1.35.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

resolution: workspace
