name: infrastructure_branch
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  flutter_branch_sdk: ^8.6.0
  freezed_annotation: any
  intl: any
  json_annotation: any
  packages_core:
    path: ../../core
  packages_domain:
    path: ../../domain
  riverpod: any
  riverpod_annotation: any

dev_dependencies:
  build_runner: any
  custom_lint: any
  freezed: any
  json_serializable: any
  nilts: any
  pedantic_mono: any
  riverpod_generator: any
  riverpod_lint: any

resolution: workspace
