name: packages_designsystem
description: "This package provides style definitions, themes, etc."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.9.0
  flutter: ^3.35.1

resolution: workspace

dependencies:
  adaptive_dialog: ^2.4.0
  animations: any
  collection: any
  dynamic_color: any
  flutter:
    sdk: flutter
  flutter_hooks: any
  flutter_svg: any
  freezed_annotation: any
  gap: any
  gauge_indicator: any
  google_fonts: ^6.2.1
  hooks_riverpod: any
  linked_scroll_controller: any
  material_color_utilities: any
  nested: any
  packages_application:
    path: ../application
  packages_domain:
    path: ../domain
  responsive_framework: ^1.5.1
  riverpod_annotation: any
  shimmer: any
  slang: any
  slang_flutter: any
  sliver_tools: any
  store_redirect: any
  url_launcher: any

dev_dependencies:
  build_runner: any
  custom_lint: any
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter
  freezed: any
  nilts: any
  pedantic_mono: any
  riverpod_generator: any
  riverpod_lint: any
  slang_build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf

flutter_gen:
  output: lib/src/gen/assets
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true
