name: packages_designsystem
description: "This package provides style definitions, themes, etc."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.1
  flutter: ^3.38.3

resolution: workspace

dependencies:
  adaptive_dialog: ^2.5.0
  animations: ^2.1.1
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  cross_file: ^0.3.5+1
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  gauge_indicator: ^0.4.3
  google_fonts: ^6.3.2
  hooks_riverpod: ^3.0.3
  image_picker: ^1.2.1
  intl: ^0.20.2
  linked_scroll_controller: ^0.2.0
  lottie: ^3.3.2
  material_color_utilities: ^0.11.1
  nested: ^1.0.0
  packages_application:
    path: ../application
  packages_core:
    path: ../core
  packages_domain:
    path: ../domain
  permission_handler: ^12.0.1
  reactive_forms: ^18.2.0
  reactive_image_picker: ^8.0.1
  responsive_framework: ^1.5.1
  riverpod_annotation: ^3.0.3
  shimmer: ^3.0.0
  slang: ^4.10.1
  slang_flutter: ^4.10.0
  sliver_tools: ^0.2.12
  store_redirect: ^2.0.4
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  nilts: ^0.25.1
  pedantic_mono: ^1.35.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  slang_build_runner: ^4.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf

flutter_gen:
  output: lib/src/gen/assets
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true
