name: infrastructure_shared_preferences
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.1

dependencies:
  packages_core:
    path: ../../core
  packages_domain:
    path: ../../domain
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  nilts: ^0.23.1
  pedantic_mono: ^1.12.3
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

resolution: workspace
