name: packages_application
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.1
  flutter: ^3.38.3

resolution: workspace

dependencies:
  collection: ^1.19.1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  image_gallery_saver_plus: ^4.0.1
  material_design_icons_flutter: ^7.0.7296
  nested: ^1.0.0
  packages_core:
    path: ../../packages/core
  packages_domain:
    path: ../../packages/domain
  reactive_forms: ^18.2.0
  reactive_forms_annotations: ^8.0.1
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  share_plus: ^11.1.0
  slang: ^4.10.1
  slang_flutter: ^4.10.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.3
  nilts: ^0.25.1
  pedantic_mono: ^1.35.0
  reactive_forms_generator: ^8.0.3
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  slang_build_runner: ^4.10.0
