name: packages_application
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.9.0
  flutter: ^3.35.1

resolution: workspace

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  image_gallery_saver_plus: ^4.0.1
  material_design_icons_flutter: ^7.0.7296
  nested: ^1.0.0
  packages_core:
    path: ../../packages/core
  packages_domain:
    path: ../../packages/domain
  reactive_forms: ^18.1.1
  reactive_forms_annotations: ^8.0.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  share_plus: ^11.1.0
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  nilts: ^0.23.1
  pedantic_mono: ^1.12.3
  reactive_forms_generator: ^8.0.3
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  slang_build_runner: ^4.8.1
