name: infrastructure_revenue_cat
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.1

dependencies:
  envied: ^1.3.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  packages_core:
    path: ../../core
  packages_domain:
    path: ../../domain
  purchases_flutter: ^9.9.8
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  envied_generator: ^1.3.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  nilts: ^0.25.1
  pedantic_mono: ^1.35.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

resolution: workspace
