name: packages_core
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.1

dependencies:
  logger: ^2.6.1
  riverpod: ^3.0.3
  uuid: ^4.5.1

dev_dependencies:
  custom_lint: ^0.8.1
  nilts: ^0.25.1
  pedantic_mono: ^1.35.0
  riverpod_lint: ^3.0.3

resolution: workspace
