name: infrastructure_mock
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  packages_core:
    path: ../../core
  packages_domain:
    path: ../../domain

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0
  nilts: ^0.23.1
  pedantic_mono: ^1.12.3
  riverpod_lint: ^2.6.5

resolution: workspace
