name: packages_domain
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.1

dependencies:
  cross_file: ^0.3.5+1
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  nilts: ^0.25.1
  pedantic_mono: ^1.35.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  test: ^1.26.2

resolution: workspace
