name: packages_domain
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  cross_file: ^0.3.4+2
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  nilts: ^0.23.1
  pedantic_mono: ^1.12.3
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  test: ^1.26.2

resolution: workspace
