name: flutter_app
description: 子供と大人で利用する、家族のための欲しい物リストアプリ
publish_to: "none"
version: 1.0.10+25

environment:
  sdk: ^3.10.1
  flutter: ^3.38.3

resolution: workspace

dependencies:
  adaptive_dialog: ^2.5.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_settings_ui: ^3.0.1
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.2.3
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  gauge_indicator: ^0.4.3
  go_router: ^17.0.0
  hooks_riverpod: ^3.0.3
  image_picker: ^1.2.1
  intl: ^0.20.2
  introduction_screen: ^4.0.0
  lottie: ^3.3.2
  material_design_icons_flutter: ^7.0.7296
  nested: ^1.0.0
  package_info_plus: ^9.0.0
  packages_application:
    path: ../../packages/application
  packages_core:
    path: ../../packages/core
  packages_dependency_override:
    path: ../../packages/dependency_override
  packages_designsystem:
    path: ../../packages/designsystem
  packages_domain:
    path: ../../packages/domain
  packages_infra_ui:
    path: ../../packages/infra_ui
  path_provider: ^2.1.5
  pattern_formatter: ^4.0.1
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  reactive_cupertino_text_field: ^2.1.2
  reactive_date_time_picker: ^5.0.1
  reactive_flutter_rating_bar: ^2.0.2
  reactive_forms: ^18.2.0
  reactive_image_picker: ^8.0.1
  responsive_framework: ^1.5.1
  riverpod_annotation: ^3.0.3
  shimmer: ^3.0.0
  slang: ^4.10.1
  slang_flutter: ^4.10.0
  url_launcher: ^6.3.2
  version: ^3.0.2

dev_dependencies:
  alchemist: ^0.13.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  go_router_builder: ^4.1.1
  json_serializable: ^6.11.2
  nilts: ^0.25.1
  pedantic_mono: ^1.35.0
  # reactive_forms_generator: ^8.1.0-beta0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  slang_build_runner: ^4.10.0

flutter:
  uses-material-design: true

  # Assets & Fonts
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
    - family: Murecho
      fonts:
        - asset: assets/fonts/Murecho-VariableFont_wght.ttf

# App Icon
flutter_launcher_icons:
  # https://zenn.dev/tsuruo/articles/eae9dbbad8372f#themed-app-icons
  # https://blog.okaryo.io/20221127-support-themed-app-icon-in-flutter-app-for-android-13
  android: true
  ios: true
  image_path: "assets/lancher_icons/AppIcon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/lancher_icons/AppIcon_foreground.png"
  # monochromeIconを作成する場合に以下を指定して一度生成する方法が一番楽かな？
  # `/android/app/src/main/res/**/ic_launcher_foreground.png`を全て`ic_launcher_monochrome.png`にリネーム
  # `android/res/mipmap-anydpi-v26/ic_launcher.xml`にmonochrome分を追加すれば完了
  # adaptive_icon_foreground: "assets/lancher_icons/AppIcon_foreground_monochrome.png"

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true

flutter_intl:
  enabled: true
