name: Create Release Branch and PR

on:
  workflow_dispatch:
    inputs:
      release_type:
        required: true
        type: choice
        description: バージョンアップする対象を指定します。
        options:
          - major
          - minor
          - patch
          - build
        default: "build"

jobs:
  create_release_branch:
    name: Create Release Branch
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      # Ciderセットアップ
      - name: Activate cider
        run: dart pub global activate cider

      # バージョンアップ
      - name: Bump version
        run: |
          cd apps/app
          cider bump ${{ github.event.inputs.release_type }} --bump-build

      # バージョンを取得
      - name: Get new version
        run: |
          cd apps/app
          echo "new_version=$(cider version)" >> $GITHUB_ENV

      # Git設定
      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # バージョンアップの変更をコミット
      - name: Commit version bump
        run: |
          git add .
          git commit -m "chore: bump version to ${{ env.new_version }}"

      # releasブランチを作成
      - name: Create and push release branch
        env: 
          NEW_BRANCH: 'release/v${{ env.new_version }}'
        run: |
          git checkout -b "release/v$NEW_BRANCH"
          git push origin "release/v$NEW_BRANCH"
      # PRを作成
      - name: Create PR for release
        env: 
          NEW_BRANCH: 'release/v${{ env.new_version }}'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --base ${{ github.ref_name }} --head release/v$NEW_BRANCH --title "Release $NEW_BRANCH" --body ""
          
