name: Version Up Major

on:
  workflow_dispatch:

jobs:
  version-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Activate cider
        run: dart pub global activate cider

      - name: Bump version
        run: cider bump major --yes

      - name: Get new version
        id: get_version
        run: echo "::set-output name=version::$(cider version)"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: Version up to ${{ steps.get_version.outputs.version }}'
          branch: release/v${{ steps.get_version.outputs.version }}
          base: main
          title: 'Release v${{ steps.get_version.outputs.version }}'
          body: |
            ## 概要
            バージョンをv${{ steps.get_version.outputs.version }}に更新します。

            ## 変更点
            - pubspec.yamlのバージョンを更新
            - CHANGELOG.mdを更新
